### ISSUE TITLE
我想问问决斗版的扫雷

### ISSUE THREAD

**Issue by TIAN-LUO** [eggggi/mine_sweeper#2]
priconne文件夹下的daylimiter 是额外自己写的还是插件自带的

**Comment by eggggi** [comment]
这个是贵族游戏作者魔改的猜头像附带的，可以看看这里https://github.com/Rs794613/PcrDuel/releases

**Comment by TIAN-LUO** [comment]
> 这个是贵族游戏作者魔改的猜头像附带的，可以看看这里https://github.com/Rs794613/PcrDuel/releases

我用的别的版本魔改的猜头像 没有这个文件 满脸懵逼 感谢回复
